apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-gateway-%s" (include "common.names.fullname" .) "tls-cert" }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | indent 4 }}
    {{- end }}
type: Opaque
data:
  {{- if and (.Files.Get "cert/job_server.p12") (.Files.Get "cert/job_server.truststore") }}
  job_server.p12: {{ .Files.Get "cert/job_server.p12" | b64enc }}
  job_server.truststore: {{ .Files.Get "cert/job_server.truststore" | b64enc }}
  {{- else }}
  job_server.p12: {{ .Values.gatewayConfig.server.ssl.p12.base64Content | quote }}
  job_server.truststore: {{ .Values.gatewayConfig.server.ssl.truststore.base64Content | quote }}
  {{- end }}
  keystore.password: {{ .Values.gatewayConfig.server.ssl.keystore.password | b64enc | quote }}
  truststore.password: {{ .Values.gatewayConfig.server.ssl.truststore.password | b64enc | quote }}

